"""phase 4 payments idempotency webhooks settlements

Revision ID: 14d15d5ad668
Revises: 1256962ac061
Create Date: 2026-06-23 17:28:50.602239

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14d15d5ad668"
down_revision: str | Sequence[str] | None = "1256962ac061"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # idempotency_keys must exist before payments (payments.idempotency_key_id
    # FKs into it) -- moved ahead of autogenerate's alphabetical table order.
    op.create_table(
        "idempotency_keys",
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform_user_id",
            "endpoint",
            "idempotency_key",
            name="ux_idempotency_keys_user_endpoint_key",
        ),
    )
    op.create_table(
        "payments",
        sa.Column("installment_id", sa.UUID(), nullable=False),
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=False),
        sa.Column("initiated_by", sa.UUID(), nullable=False),
        sa.Column("commission_config_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key_id", sa.UUID(), nullable=True),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("squad_transaction_ref", sa.String(), nullable=False),
        sa.Column("squad_virtual_account_number", sa.String(), nullable=True),
        sa.Column("squad_virtual_account_bank", sa.String(), nullable=True),
        sa.Column("va_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("raw_squad_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('initiated', 'success', 'mismatch', 'expired', 'failed')",
            name="ck_payments_status",
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["commission_config_id"],
            ["commission_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["idempotency_key_id"],
            ["idempotency_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by"],
            ["platform_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["installment_id"],
            ["premium_installments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("squad_transaction_ref"),
    )
    op.create_index(
        "ix_payments_installment_id_status", "payments", ["installment_id", "status"], unique=False
    )
    op.create_table(
        "webhook_events",
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("transaction_ref", sa.String(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("processing_status", sa.String(), nullable=False),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status IN ('pending', 'processed', 'rejected', 'failed')",
            name="ck_webhook_events_processing_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transaction_ref", "event_type", name="ux_webhook_events_transaction_ref_event_type"
        ),
    )
    op.create_table(
        "settlement_payouts",
        sa.Column("insurance_company_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("squad_transfer_ref", sa.String(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("previous_attempt_id", sa.UUID(), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("raw_squad_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source_type IN ('payment')", name="ck_settlement_payouts_source_type"),
        sa.CheckConstraint(
            "status IN ('pending', 'success', 'failed')", name="ck_settlement_payouts_status"
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_attempt_id"],
            ["settlement_payouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("squad_transfer_ref"),
    )
    op.create_index(
        "ix_settlement_payouts_source",
        "settlement_payouts",
        ["source_type", "source_id"],
        unique=False,
    )
    op.add_column(
        "insurance_companies", sa.Column("settlement_bank_code", sa.String(), nullable=True)
    )
    op.add_column(
        "insurance_companies", sa.Column("settlement_account_number", sa.String(), nullable=True)
    )
    op.add_column(
        "insurance_companies", sa.Column("settlement_account_name", sa.String(), nullable=True)
    )
    op.add_column("premium_installments", sa.Column("payment_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_premium_installments_payment_id",
        "premium_installments",
        "payments",
        ["payment_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_premium_installments_payment_id", "premium_installments", type_="foreignkey"
    )
    op.drop_column("premium_installments", "payment_id")
    op.drop_column("insurance_companies", "settlement_account_name")
    op.drop_column("insurance_companies", "settlement_account_number")
    op.drop_column("insurance_companies", "settlement_bank_code")
    op.drop_index("ix_settlement_payouts_source", table_name="settlement_payouts")
    op.drop_table("settlement_payouts")
    op.drop_table("webhook_events")
    op.drop_index("ix_payments_installment_id_status", table_name="payments")
    op.drop_table("payments")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
