"""phase 2 policyholders policies installments reminders

Revision ID: f2da08e5a709
Revises: 37c595f4470a
Create Date: 2026-06-22 21:23:41.843495

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2da08e5a709"
down_revision: str | Sequence[str] | None = "37c595f4470a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policyholders",
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("identification_number", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policies",
        sa.Column("policyholder_id", sa.UUID(), nullable=False),
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=False),
        sa.Column("policy_type", sa.String(), nullable=False),
        sa.Column("premium_amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("premium_frequency", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "premium_frequency IN ('monthly', 'quarterly', 'annually')",
            name="ck_policies_premium_frequency",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'lapsed', 'cancelled')", name="ck_policies_status"
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policyholder_id"],
            ["policyholders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "premium_installments",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('due', 'overdue', 'paid', 'cancelled')",
            name="ck_premium_installments_status",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "policy_id", "due_date", name="ux_premium_installments_policy_due_date"
        ),
    )
    op.create_index(
        "ix_premium_installments_status_due_date",
        "premium_installments",
        ["status", "due_date"],
        unique=False,
    )
    op.create_table(
        "reminders",
        sa.Column("installment_id", sa.UUID(), nullable=False),
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("sent_by", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('email')", name="ck_reminders_channel"),
        sa.CheckConstraint("status IN ('queued', 'sent', 'failed')", name="ck_reminders_status"),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["installment_id"],
            ["premium_installments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_by"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reminders")
    op.drop_index("ix_premium_installments_status_due_date", table_name="premium_installments")
    op.drop_table("premium_installments")
    op.drop_table("policies")
    op.drop_table("policyholders")
    # ### end Alembic commands ###
