"""phase 3 commission configs and ledger

Revision ID: 1256962ac061
Revises: f2da08e5a709
Create Date: 2026-06-22 21:44:11.365287

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1256962ac061"
down_revision: str | Sequence[str] | None = "f2da08e5a709"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_accounts",
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=True),
        sa.Column("broker_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('BROKER_CLEARING', 'GTBANK_REVENUE', 'INSUREFLOW_REVENUE', "
            "'BROKER_COMMISSION', 'INSURER_PAYABLE', 'INSURER_SETTLED')",
            name="ck_ledger_accounts_account_type",
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ux_ledger_accounts_broker",
        "ledger_accounts",
        ["account_type", "broker_id"],
        unique=True,
        postgresql_where=sa.text("broker_id IS NOT NULL"),
    )
    op.create_index(
        "ux_ledger_accounts_insurer",
        "ledger_accounts",
        ["account_type", "insurance_company_id"],
        unique=True,
        postgresql_where=sa.text("insurance_company_id IS NOT NULL AND broker_id IS NULL"),
    )
    op.create_index(
        "ux_ledger_accounts_platform",
        "ledger_accounts",
        ["account_type"],
        unique=True,
        postgresql_where=sa.text("insurance_company_id IS NULL AND broker_id IS NULL"),
    )
    op.create_table(
        "commission_configs",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=True),
        sa.Column("broker_id", sa.UUID(), nullable=True),
        sa.Column("gtbank_rate_bps", sa.Integer(), nullable=False),
        sa.Column("insureflow_rate_bps", sa.Integer(), nullable=False),
        sa.Column("broker_rate_bps", sa.Integer(), nullable=True),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global' AND insurance_company_id IS NULL AND broker_id IS NULL) OR "
            "(scope = 'insurance_company' AND insurance_company_id IS NOT NULL) OR "
            "(scope = 'broker' AND broker_id IS NOT NULL)",
            name="ck_commission_configs_scope_fk_consistency",
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'insurance_company', 'broker')", name="ck_commission_configs_scope"
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["platform_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ux_commission_configs_active_broker",
        "commission_configs",
        ["broker_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL AND scope = 'broker'"),
    )
    op.create_index(
        "ux_commission_configs_active_global",
        "commission_configs",
        ["scope"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL AND scope = 'global'"),
    )
    op.create_index(
        "ux_commission_configs_active_insurer",
        "commission_configs",
        ["insurance_company_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL AND scope = 'insurance_company'"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("ledger_account_id", sa.UUID(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("reference_type", sa.String(), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column("posting_group_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('debit', 'credit')", name="ck_ledger_entries_entry_type"
        ),
        sa.CheckConstraint("amount_kobo > 0", name="ck_ledger_entries_amount_positive"),
        sa.ForeignKeyConstraint(
            ["ledger_account_id"],
            ["ledger_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ledger_entries_posting_group_id", "ledger_entries", ["posting_group_id"], unique=False
    )
    op.create_index(
        "ix_ledger_entries_reference",
        "ledger_entries",
        ["reference_type", "reference_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Seed the global commission config row (PRD §9 confirmed defaults:
    # GTBank 50bps / Insureflow 50bps). Every commission resolution falls
    # back to this row when no broker/insurer-scoped override exists, so it
    # must always exist -- there is no "no config found" path by design.
    op.execute(
        "INSERT INTO commission_configs (id, scope, gtbank_rate_bps, insureflow_rate_bps, "
        "broker_rate_bps, created_by) "
        "VALUES (gen_random_uuid(), 'global', 50, 50, NULL, NULL)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ledger_entries_reference", table_name="ledger_entries")
    op.drop_index("ix_ledger_entries_posting_group_id", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(
        "ux_commission_configs_active_insurer",
        table_name="commission_configs",
        postgresql_where=sa.text("effective_to IS NULL AND scope = 'insurance_company'"),
    )
    op.drop_index(
        "ux_commission_configs_active_global",
        table_name="commission_configs",
        postgresql_where=sa.text("effective_to IS NULL AND scope = 'global'"),
    )
    op.drop_index(
        "ux_commission_configs_active_broker",
        table_name="commission_configs",
        postgresql_where=sa.text("effective_to IS NULL AND scope = 'broker'"),
    )
    op.drop_table("commission_configs")
    op.drop_index(
        "ux_ledger_accounts_platform",
        table_name="ledger_accounts",
        postgresql_where=sa.text("insurance_company_id IS NULL AND broker_id IS NULL"),
    )
    op.drop_index(
        "ux_ledger_accounts_insurer",
        table_name="ledger_accounts",
        postgresql_where=sa.text("insurance_company_id IS NOT NULL AND broker_id IS NULL"),
    )
    op.drop_index(
        "ux_ledger_accounts_broker",
        table_name="ledger_accounts",
        postgresql_where=sa.text("broker_id IS NOT NULL"),
    )
    op.drop_table("ledger_accounts")
    # ### end Alembic commands ###
