"""phase 1: tenancy, auth, rbac, onboarding

Revision ID: 7a6cfa55a692
Revises: 5884970fc697
Create Date: 2026-06-22 20:53:10.728624

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a6cfa55a692"
down_revision: Sequence[str] | str | None = "5884970fc697"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brokers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("kyb_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'suspended')", name="ck_brokers_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_email"),
    )
    op.create_table(
        "insurance_companies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("kyb_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("settlement_mode", sa.String(), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "settlement_mode IN ('real_time', 'scheduled')",
            name="ck_insurance_companies_settlement_mode",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'suspended')",
            name="ck_insurance_companies_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_email"),
    )
    op.create_table(
        "broker_insurer_assignments",
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ux_broker_insurer_assignments_active_broker",
        "broker_insurer_assignments",
        ["broker_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "platform_users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("insurance_company_id", sa.UUID(), nullable=True),
        sa.Column("broker_id", sa.UUID(), nullable=True),
        sa.Column("activation_token_hash", sa.String(), nullable=True),
        sa.Column("activation_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'insureflow_admin' AND insurance_company_id IS NULL AND broker_id IS NULL) "
            "OR (role = 'insurance_company_admin' AND insurance_company_id IS NOT NULL "
            "AND broker_id IS NULL) "
            "OR (role IN ('broker_admin', 'broker_staff') AND broker_id IS NOT NULL "
            "AND insurance_company_id IS NULL)",
            name="ck_platform_users_role_scope",
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["insurance_company_id"],
            ["insurance_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_users")
    op.drop_index(
        "ux_broker_insurer_assignments_active_broker",
        table_name="broker_insurer_assignments",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("broker_insurer_assignments")
    op.drop_table("insurance_companies")
    op.drop_table("brokers")
    # ### end Alembic commands ###
